### ISSUE TITLE
SH2 E3 Build  SLPM_123.45_123.45 

### ISSUE THREAD

**Issue by noanj** [SamusAranX/SH2Unpack#1]
Hey hello. Is it possible to make an unpacker and packer for the SLPM_123.45 build?

**Comment by SamusAranX** [comment]
Creating/packing new MGF files is currently beyond the scope of this project. I do accept PRs that add that functionality, though.

As for unpacking that specific game version, it's *supposed* to be possible, but I think the code needs tweaking. I'll get around to it eventually.

**Comment by noanj** [comment]
> Creating/packing new MGF files is currently beyond the scope of this project. I do accept PRs that add that functionality, though.
> 
> As for unpacking that specific game version, it's _supposed_ to be possible, but I think the code needs tweaking. I'll get around to it eventually.

It would be great. MGFiler can do this, but not with e3build.

**Comment by SamusAranX** [comment]
The [latest release](https://github.com/SamusAranX/SH2Unpack/releases/latest) can now unpack all known versions of the game. As I said, a repacker isn't planned, but I hope this helps in the meantime.
